Check if the preprocessor exists.

diff --git a/bin/loadxresources b/bin/loadxresources
--- a/bin/loadxresources
+++ b/bin/loadxresources
@@ -3,8 +3,15 @@
 # Description:	loads the xresources from my custom directory
 #
 
+# Check if Preprocessor exists.
+if ! command -v cpp 2>&1 >/dev/null; then
+	echo "Error: Unable to find a preprocessor." >&2
+	exit 1
+fi
+
 [ -f $HOME/.Xresources ] && xrdb \
 	-DDPI="$DPI" \
 	-DUI_FONT="$UI_FONT" \
 	-DI3_STATUS_CMD="$I3_STATUS_CMD" \
 	$HOME/.Xresources
+
